spring:
  # springMVC配置
  mvc:
    hiddenmethod:
      filter:
        enabled: true  # 开启restful支持
    #  设置druid数据源
  datasource:
    # 数据源基本配置
    username: root
    password: zhao17615110273
    url: jdbc:mysql://127.0.0.1:3306/mybatis?characterEncoding=UTF-8&serverTimezone=GMT%2B8&allowMultiQueries=true
    driver‐class‐name: com.mysql.cj.jdbc.Driver # 注意MySQL8.x的驱动
    type: com.alibaba.druid.pool.DruidDataSource
    #   数据源高级配置
    initialSize: 5                          # 初始化大小
    minIdle: 5                              # 最小
    maxActive: 20                           # 最大
    maxWait: 60000                          # 获取连接等待超时的时间
    timeBetweenEvictionRunsMillis: 60000  # 检测间隔，检测需要关闭空闲连接，单位ms
    minEvictableIdleTimeMillis: 300000    # 一个连接在池中最小生存时间
    validationQuery: SELECT 1 FROM DUAL   # 检测sql语句
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

mybatis:
  #  config‐location: classpath:mybatis/mybatis-config.xml #指定mybatis全局配置文件的位置
  mapper‐locations: classpath:mybatis/mapper/**/*.xml      #指定sql映射文件的位置
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.haoqian.config.domain
